# Regressão Linear Multivariada - Trabalho

## Estudo de caso: Qualidade de Vinhos

Nesta trabalho, treinaremos um modelo de regressão linear usando descendência de gradiente estocástico no conjunto de dados da Qualidade do Vinho. O exemplo pressupõe que uma cópia CSV do conjunto de dados está no diretório de trabalho atual com o nome do arquivo *winequality-white.csv*.

O conjunto de dados de qualidade do vinho envolve a previsão da qualidade dos vinhos brancos em uma escala, com medidas químicas de cada vinho. É um problema de classificação multiclasse, mas também pode ser enquadrado como um problema de regressão. O número de observações para cada classe não é equilibrado. Existem 4.898 observações com 11 variáveis de entrada e 1 variável de saída. Os nomes das variáveis são os seguintes:

1. Fixed acidity.
2. Volatile acidity.
3. Citric acid.
4. Residual sugar.
5. Chlorides.
6. Free sulfur dioxide. 
7. Total sulfur dioxide. 
8. Density.
9. pH.
10. Sulphates.
11. Alcohol.
12. Quality (score between 0 and 10).

O desempenho de referencia de predição do valor médio é um RMSE de aproximadamente 0.148 pontos de qualidade.

Utilize o exemplo apresentado no tutorial e altere-o de forma a carregar os dados e analisar a acurácia de sua solução.

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from csv import reader
from random import randrange
from math import sqrt
from sklearn.metrics import accuracy_score, classification_report

In [58]:
def predict(row, coefficients):
    yhat = coefficients[0]
    for i in range(len(row)-1):
        yhat += coefficients[i + 1] * row[i]
    return yhat

def coefficients_sgd(train, l_rate, n_epoch):
    coef = [0.0 for i in range(len(train[0]))]
    for epoch in range(n_epoch):
        sum_error = 0
        for row in train:
            yhat = predict(row, coef)
            error = yhat - row[-1]
            sum_error += error**2
            coef[0] = coef[0] - l_rate * error
            for i in range(len(row)-1):
                coef[i + 1] = coef[i + 1] - l_rate * error * row[i] 
    return coef

In [59]:
df = pd.read_csv('winequality-white.csv',names = ["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"])
df.head()
#Por algum motivo que não sei qual é, em casa está dando erro de vez em quando na hora da leitura dos dados

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,"fixed acidity;""volatile acidity"";""citric acid""...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
for f in ["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"]:
    df[f] = df[f].astype('category')
    df[f] = df[f].cat.codes

In [61]:
features = ["fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"]
X = df.get(features)
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,3961,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,3485,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,952,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,3591,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,2584,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
5,2584,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6,3591,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7,750,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8,3485,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
9,952,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
10,3573,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
11,3586,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
12,3768,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
13,3337,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
14,1393,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
15,3700,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
16,1400,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
17,961,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
18,810,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
19,2934,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
20,1313,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
21,810,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
22,1122,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
23,1925,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
24,3179,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
25,1503,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
26,3475,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
27,2108,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
28,3496,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
29,2892,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
4869,321,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4870,1458,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4871,605,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4872,507,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4873,2374,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4874,237,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4875,204,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4876,2859,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4877,784,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4878,493,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4879,808,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4880,1555,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4881,1555,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4882,499,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4883,147,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4884,36,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4885,1326,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4886,1556,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4887,676,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4888,800,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4889,1871,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4890,32,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4891,613,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4892,236,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4893,1247,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4894,677,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4895,1540,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4896,1250,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4897,144,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4898,2267,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [62]:
Y = df['quality'].values

Y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int8)

In [63]:
X = MinMaxScaler().fit_transform(X)
ds = np.column_stack([X, Y])
print(ds)

[[ 1.          0.          0.         ...,  0.          0.         -1.        ]
 [ 0.87982833  0.          0.         ...,  0.          0.         -1.        ]
 [ 0.24034335  0.          0.         ...,  0.          0.         -1.        ]
 ...,
 [ 0.31557687  0.          0.         ...,  0.          0.         -1.        ]
 [ 0.03635446  0.          0.         ...,  0.          0.         -1.        ]
 [ 0.57233022  0.          0.         ...,  0.          0.         -1.        ]]

In [64]:
train, test = train_test_split(ds, test_size = 0.3)

In [65]:
l_rate = 0.0001
n_epoch = 100

coefs = coefficients_sgd(train, l_rate, n_epoch)
print(coefs)

[-0.97411004182526784, -0.048095405333204354, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [66]:
predictions = list()
for row in test:
    predicted = predict(row, coefs)
    predictions.append(predicted)

In [67]:
y_test = list()
for i in range(1470):
    y_test.append(test[i][11])

In [68]:
predicted = predictions

In [69]:
soma = 0
for i in range(len(y_test)):
    erro = predicted[i] - y_test[i]
    soma += (erro**2)
    erroMedio = soma/float(len(y_test))
acc = sqrt(erroMedio)

In [70]:
acc

0.9990290936297678

In [71]:
#erro deixou o resultado de acuracia absurdamente certeiro, oq quer dizer que está inválido, caso le-se corretamente os dados